github: [metadata]

remote_theme: eclipsefdn/jekyll-theme-eclipsefdn
#theme: jekyll-theme-eclipsefdn # for local execution

title: [Eclipse Yasson]
description: [Yasson is a Java framework which provides a standard binding layer between Java classes and JSON documents]

links:
  source: https://github.com/eclipse-ee4j/yasson
  #docs: documentation
  javadocs: https://www.javadoc.io/doc/org.eclipse/yasson
  download: https://github.com/eclipse-ee4j/yasson/releases
  mailinglist: https://accounts.eclipse.org/mailing-list/yasson-dev
  #faq: FAQ
